app/blog/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, BooleanField, SubmitField
from wtforms.validators import DataRequired, Optional, Length, Email
from wtforms.fields.html5 import DateField
from flask_pagedown.fields import PageDownField
import datetime


class SearchForm(FlaskForm):
    search = StringField('search', validators=[DataRequired()])


class ProfileForm(FlaskForm):
    name = StringField('Name', validators=[Optional(), Length(1, 64)])
    location = StringField('Location', validators=[Optional(), Length(1, 64)])
    bio = TextAreaField('Bio')
    submit = SubmitField('Submit')


class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired(), Length(1, 255)])
    subtitle = StringField('Sub-Title', validators=[DataRequired(), Length(1, 255)])
    body = TextAreaField('Body')
    # date = DateField('Date')
    submit = SubmitField('Submit')

    def from_model(self, post):
        self.title.data = post.title
        self.subtitle.data = post.subtitle
        self.body.data = post.body
        self.date.data = post.date

    def to_model(self, post):
        post.title = self.title.data
        post.subtitle = self.subtitle.data
        post.body = self.body.data
        post.date = datetime.datetime.now()


class AdminCommentForm(FlaskForm):
    body = PageDownField('Comment', validators=[DataRequired()])
    submit = SubmitField('Submit')


class CommentForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired(), Length(1, 64)])
    email = StringField('Email', validators=[DataRequired, Length(1, 64), Email()])
    body = PageDownField('Comment', validators=[DataRequired()])
    notify = BooleanField('Notify when new comments are posted', default=True)
    submit = SubmitField('Submit')

app/blog/__init__.py
from flask import Blueprint
blog = Blueprint('blog', __name__)
from . import routes

app/blog/routes.py
from flask import render_template, flash, redirect, url_for, abort, request, current_app, Markup
from . import blog
from flask_login import login_required, current_user
from .. import db
from ..models import User, Post
from .forms import ProfileForm, PostForm, CommentForm, AdminCommentForm


@blog.route('/')
def blog_home():
    # db.create_engine()  # TODO - need to re-establish connection automatically
    page = request.args.get('page', 1, type=int)
    pagination = Post.query.order_by(Post.post_date.desc())\
        .paginate(page, per_page=current_app.config['TALKS_PER_PAGE'], error_out=False)
    post_list = pagination.items
    return render_template('blog/blog.html', posts=post_list, pagination=pagination)


@blog.route('/new', methods=['GET', 'POST'])
@login_required  # TODO - Require login for creating a new blog post
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(author_id=current_user.get_id())
        form.to_model(post)
        db.session.add(post)
        db.session.commit()
        flash('Your post was added successfully!')
        return redirect(url_for('.blog_home'))
    return render_template('blog/new_post.html', form=form)


@blog.route('/<int:post_id>', methods=['GET', 'POST'])
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('blog/post.html',
                           post=post)



@blog.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():
    form = ProfileForm()
    if form.validate_on_submit():
        current_user.name = form.name.data
        current_user.location = form.location.data
        current_user.bio = form.bio.data
        db.session.add(current_user._get_current_object())
        db.session.commit()
        flash('Your profile has been updated.')
        return redirect(url_for('blog.blog_home'))
    form.name.data = current_user.name
    form.location.data = current_user.location
    form.bio.data = current_user.bio
    return render_template('blog/profile.html', form=form)

app/templates/blog/_post.html
{#<!--<div class="post-preview">-->#}
{#    <!--<a href="{{url_for('blog.post', post_id = post.id)}}">-->#}
{#        <!--<h2 class="post-title">-->#}
{#            <!--{{post.title}}-->#}
{#        <!--</h2>-->#}
{#        <!--<h3 class="post-subtitle">-->#}
{#            <!--{{post.subtitle}}-->#}
{#        <!--</h3>-->#}
{#    <!--</a>-->#}
{#    <!--<p class="post-meta">Posted by {{post.author.name}} on {{post.post_date}}</p>-->#}
{#<!--</div>-->#}
{#<!--<hr>-->#}


<div class="post-snippet mb64">
    <!--<a href="{{url_for('blog.post', post_id = post.id)}}">-->
        <img class="mb24" alt="Post Image" src="{{post.stream_picture}}"/>
    <!--</a>-->
    <div class="post-title">
        <span class="label">{{post.post_date}}</span>
        <a href="{{url_for('blog.post', post_id = post.id)}}">
            <h4 class="inline-block">{{post.title}}</h4>
        </a>
    </div>
    <ul class="post-meta">
        <li>
            <i class="ti-user"></i>
<span>Written by
<a href="#">{{post.author.name}}</a>
</span>
        </li>
        <li>
            <i class="ti-tag"></i>
<span>Tagged as
<a href="#">
    {{post.tag.tag_desc}}
</a>
</span>
        </li>
    </ul>
    <hr>
    <p>
        {{post.subtitle}}
    </p>
    <a class="btn btn-sm" href="{{url_for('blog.post', post_id = post.id)}}">Read More</a>
</div>

app/templates/blog/blog.html
<!DOCTYPE html>
{% extends "template.html" %}
<html lang="en" class="no-js">

{% block head %}
{{ super() }}
<link href="{{ url_for('static', filename='css/custom-blog.css') }}" rel="stylesheet" type="text/css" media="all"/>
{% endblock head %}

<body>

{% block navbar %}
{{ super() }}
{% endblock navbar %}

<div class="main-container">
    {% block content %}
    <section class="fullscreen image-bg">
        <div class="background-image-holder">
            <img alt="image" class="background-image" src="https://s3.amazonaws.com/anthonycarminati-backgrounds/carminatiio/typewriter_keys.jpg"/>
        </div>
        <div class="container v-align-transform">
            <div class="row">
                <div class="col-sm-12 text-center">
                    <h2 class="uppercase large mb8">
                        Welcome to my blog
                    </h2>
                    <h4 class="mb0">Enjoy. Contribute. Share.</h4>
                </div>
            </div>
        </div>
    </section>
    <section>
        <div class="container">
            <div class="row">
                <div class="col-md-10 col-md-offset-1">
                    {% for post in posts %}
                    {% include "blog/_post.html" %}
                    {% endfor %}

                    <div class="text-center">
                        {% if posts %}
                        <ul class="pagination">
                            {% if pagination.has_prev %}
                            <li>
                                <a href="{{ url_for('blog.blog_home', page=pagination.prev_num) }}">
                                    &laquo; Newer
                                </a>
                            </li>
                            {% endif %}

                            {% if pagination.has_next %}
                            <li>
                                <a href="{{ url_for('blog.blog_home', page=pagination.next_num) }}">
                                    Older &raquo;
                                </a>
                            </li>
                            {% endif %}
                        </ul>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </section>
    {% endblock content %}

    {% block footer %}
    {{super()}}
    {% endblock footer %}

</div>


{% block script %}
{{ super() }}
{% endblock script %}
</body>
</html>

app/templates/blog/new_post.html
{% extends "template.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
<div class="container">
    <div class="page-header">
        <h1>New Blog Post</h1>
    </div>
</div>

<div class="container">
    <div class="row">
        {{ wtf.quick_form(form) }}
    </div>
</div>
{% endblock content%}

app/templates/blog/post.html
<!DOCTYPE html>
{% extends "template.html" %}
<html lang="en">

{% block head %}
    {{ super() }}
{% endblock head %}

<body>
{% block navbar %}
    {{ super() }}
{% endblock navbar %}

{% block content %}
{#    <header class="intro-header"
            style="background-image: url('https://s3.amazonaws.com/anthonycarminati-backgrounds/carminatiio/typewriter_keys.jpg')">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="site-heading">
                        <h1>{{ post.title }}</h1>
                        <hr class="small">
                        <span class="subheading">{{ post.subtitle }}</span>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                {{ post.body|markdown }}
            </div>
        </div>
    </div>

    <div id="disqus_thread"></div>

    <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a>
    </noscript>#}

    <div class="main-container">
        <section>
            <div class="container">
                <div class="row">
                    <div class="col-sm-10 col-sm-offset-1">
                        <div class="post-snippet mb64">
                            <div class="post-title">
                                <h4 class="inline-block">{{ post.title }}</h4>
                            </div>
                            <ul class="post-meta">
                                <li>
                                    <i class="ti-user"></i>
                                        <span>Written by
                                            <a href="#">
                                                    {{ post.author.name }}
                                            </a>
                                        </span>
                                </li>
                                <li>
                                    <i class="ti-tag"></i>
                                        <span>Tagged as
                                            <a href="#">
                                                    {{ post.tag.tag_desc }}
                                            </a>
                                        </span>
                                </li>
                            </ul>
                            <hr>
                            {{ post.body }}
                            <p class="lead">
                                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna
                                aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                            </p>
                            <p>
                                At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque
                                corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui
                                officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita
                                distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime
                                placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus.
                            </p>
                            <blockquote>
                                It's our challenges and obstacles that give us layers of depth and make us interesting. Are they fun when they happen?
                                No. But they are what make us unique. And that's what I know for sure... I think.
                            </blockquote>
                            <p>
                                Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam,
                                eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam
                                voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione
                                voluptatem sequi nesciunt.
                            </p>
                            <ul class="bullets">
                                <li>Beatae vitae dicta sunt explicabo</li>
                                <li>Inventore veritatis et quasi architecto</li>
                                <li>Sed do eiusmod tempor incididunt</li>
                                <li>Accusamus et iusto odio dignissimos ducimus</li>
                            </ul>
                        </div>
                        <hr>
                        <div id="disqus_thread"></div>
                        <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered
                                                                                                                                 byDisqus.</a>
                        </noscript>


                        {#                        <div class="disqus-comments" data-shortname="mrarefoundry">#}
                        {#                            <div id="disqus_thread"></div>#}
                        {#                        </div>#}
                    </div>
                </div>
            </div>
        </section>

    </div>

{% endblock content %}

{% block script %}
    {{ super() }}
    <script>
        /**
         * RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
         * LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables
         */
        /*
         var disqus_config = function () {
         this.page.url = PAGE_URL; // Replace PAGE_URL with your page's canonical URL variable
         this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
         };
         */
        (function () { // DON'T EDIT BELOW THIS LINE
            var d = document, s = d.createElement('script');

            s.src = '//carminatiio.disqus.com/embed.js';

            s.setAttribute('data-timestamp', +new Date());
            (d.head || d.body).appendChild(s);
        })();
    </script>
{% endblock script %}

{% block footer %}
    {{ super() }}
{% endblock footer %}
</body>

</html>

app/templates/blog/profile.html
{% extends "template.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
<div class="container">
    <div class="page-header">
        <h1>User Profile: {{current_user.username}}</h1>
    </div>
</div>

<div class="container">
    <div class="row">
        {{ wtf.quick_form(form) }}
    </div>
</div>
{% endblock content%}